### ISSUE TITLE
Depth limiting not usable when cloning pull requests

### ISSUE THREAD

**Issue by vincentisambart** [bitrise-steplib/steps-git-clone#177]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 6.1.2
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES / NO / NOT APPLICABLE

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

As the full history of our repo is way too big, when using this step for pull requests I would like to use a depth of 1, but if you do that, this steps's call to git merge fails with a `fatal: refusing to merge unrelated histories` error, and then tries to unshallow the repository, removing any merit to limiting the depth in the first place. Setting "Manual merge" to "no" looks like it might use the merge branch automatically created by GitHub but it didn't change anything, and looking at the code even if "Manual merge" is set to "no" this step does a manual merge!? The merge branch doesn't seem to be really used anywhere.

As a work around I set the depth to something like 100, and it kinds of works but it's a ugly hack.

So for pull request, to be able to do the clone in a reasonable amount of time without having to put the full Git repo in the cache, I can see 2 possible solutions:

- When "Manual merge" is set to "no" and a merge branch is available, do not merge manually but use that merge branch (In fact when I saw "Manual merge" I thought that turning it off would do exactly that)
- You could also add an option to use `filter=tree:0` (more details at https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/), that would allow the `git merge` to fetch the needed trees without having to download the full history.

### Bitrise info

- Build URL: _Please share the build URL with us._
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES / NO_
- Log: 

<details>
  <pre>
 
  </pre>
</details>

### Steps to reproduce

1. Set-up a workflow for pull request, in your "Git Clone Repository" settings set "Limit fetching to the specified number of commits" to `1` and "Manual merge" to `no`.
2. Make your workflow run for you pull request, and look at `git-clone@6` log. You should not have a `fatal: refusing to merge unrelated histories` or any `git fetch` with a `--unshallow`.

**Comment by swarajrao** [comment]
+1, also running into this

**Comment by ofalvai** [comment]
Thank you @vincentisambart for bringing this to our attention, especially the article about the various optimization modes!

I agree that the current implementation is not optimal and you might need to use a higher depth value. I think the root cause is that the step is fetching the head of the PR branch, instead of the merge branch provided by GitHub (as you pointed out). I think the reason for this behavior is that the step needs to support a variety of Git providers, not just GitHub and this merge branch is not always available. But it's a good idea to try the merge branch first, we'll investigate this and other optimizations in the future.

Regarding the other clone options: even the article's summary is that in CI environments the best option is shallow clone. Also, the other options need to be supported by the Git backend too, and we need to support all major providers, not just GitHub.

I'll keep this issue open for further discussion and we'll post an update once we have any findings or a new step release to try.

**Comment by CraigSiemens** [comment]
I was looking into speeding up cloning for our repo as well and came to similar conclusions.

- `git fetch --depth=# ...` is unusable for any PR based workflow since it will cause merging into the base to fail.
  - It does speed up non-PR triggered builds that don't merge. To conditionally change the depth, it'd either need a dedicated workflow to customize the depth on the step, or an earlier step in the workflow that sets an environment variable of the depth by checking whether the build was triggered by a PR.
- In my testing locally, `--filter=tree:0` would work for PR workflows and ran in half the time.
  - It doesn't appear that the step has a way to pass custom flags to the fetch commands so the only way to use it would be to add a script step that mostly replicates this one.

**Comment by ofalvai** [comment]
Hello everyone!

I'm happy to announce that the latest step version ([6.2.3](https://github.com/bitrise-steplib/steps-git-clone/releases/tag/6.2.3)) fixes this specific issue for GitHub pull requests. 

The step implementation for fetching the merge ref was indeed incorrect, it was doing a manual merge, which conflicted with shallow cloning. This version is a patch release, so it doesn't make breaking changes to step input defaults, meaning that you still need to set `manual_merge=no` for a merge ref checkout.

We are also planning to make shallow clones the default in the next major version, but this will come with breaking existing step inputs and default values.
